POST http://localhost:8081/friend/addByUserName/
Content-Type: application/json 

{
    "username" : "test",
    "friendUsername" : "testFriend",
}

###
GET http://localhost:8081/friend/
Content-Type: application/json
