POST http://localhost:8081/comment/addByUsername
Content-Type: application/json 

{
    "username" : "huthifa",
    "trainLine" : "Orange",
    "comment" : "This is huthifa's test Comment using username!"
}

###
POST http://localhost:8081/comment/addByUserId
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "trainLine" : "Red",
    "comment" : "This is my test Comment using userId!"
}

###
GET http://localhost:8081/comment/
Content-Type: application/json

###
GET http://localhost:8081/comment/getByUsername/huthifa
Content-Type: application/json

###
GET http://localhost:8081/comment/getByUserId/65deb3d6336c535c1f70be27
Content-Type: application/json