# Should Pass: Valid userid, trainLine, comment
###
POST {{$processEnv REACT_APP_API_URL}}/comment/
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "trainLine" : "Red",
    "comment" : "This is my test Comment using userId!"
}

# Should Fail: Invalid userId 
###
POST {{$processEnv REACT_APP_API_URL}}/comment/
Content-Type: application/json 

{
    "userId" : "65deb3d5336c535b1f10be27",
    "trainLine" : "Red",
    "comment" : "This comment should not be added and throw user id not found Error!"
}

# Should Fail: Invalid TrainLine (add by userId)
###
POST {{$processEnv REACT_APP_API_URL}}/comment/
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "trainLine" : "InvalidTrainLine",
    "comment" : "This comment should not be added and throw trainLine not found Error!"
}

# Should Pass: Should return all the comments
###
GET {{$processEnv REACT_APP_API_URL}}/comment/
Content-Type: application/json

# Should Pass: Valid userid
###
GET {{$processEnv REACT_APP_API_URL}}/comment/getByUserId/65deb3d6336c535c1f70be27
Content-Type: application/json

# Should Fail: Invalid userid
###
GET {{$processEnv REACT_APP_API_URL}}/comment/getByUserId/65deb3d5336c535b1f10be27
Content-Type: application/json

# Should Pass: Valid trainLine
###
GET {{$processEnv REACT_APP_API_URL}}/comment/getByTrainLine/Red
Content-Type: application/json

# Should Fail: Invalid trainline
###
GET {{$processEnv REACT_APP_API_URL}}/comment/getByTrainLine/InvalidTrainLine
Content-Type: application/json