POST http://localhost:8081/favoriteLine/addByUsername
Content-Type: application/json 

{
    "username" : "User610",
    "trainLine" : "Red"
}

###
POST http://localhost:8081/favoriteLine/addByUserId
Content-Type: application/json 

{
    "userId" : "65de22f35759e9e77c171828",
    "trainLine" : "Red" 
}
###
DELETE http://localhost:8081/favoriteLine/deleteByUsername
Content-Type: application/json 

{
    "username": "User610",
    "trainLine": "Red"
}
###
DELETE http://localhost:8081/favoriteLine/deleteByUserId
Content-Type: application/json 

{
    "userId" : "65de22f35759e9e77c171828",
    "trainLine" : "Red" 
}
###
GET http://localhost:8081/favoriteLine/username/User610
Content-Type: application/json 

###
GET http://localhost:8081/favoriteLine/userId/65de22f35759e9e77c171828
Content-Type: application/json 

