POST http://localhost:8081/favoriteLine/addByUsername
Content-Type: application/json 

{
    "username" : "testtest",
    "trainLine" : "Red"
}

###
POST http://localhost:8081/favoriteLine/addByUserId
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "trainLine" : "Red" 
}
###
DELETE http://localhost:8081/favoriteLine/deleteByUsername
Content-Type: application/json 

{
    "username": "testtest",
    "trainLine": "Red"
}

###
DELETE http://localhost:8081/favoriteLine/deleteByUserId
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "trainLine" : "Red" 
}

###
# GET http://localhost:8081/favoriteLine/username/User610
# Content-Type: application/json 

# ###
# GET http://localhost:8081/favoriteLine/userId/65de22f35759e9e77c171828
# Content-Type: application/json 

