# Should Pass: valid userId, valid friendUserId
###
POST http://localhost:8081/friend/addByUserId
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "friendUserId" : "65deb6a2c488f1a40b1b85cd"
}

# Should Fail: invalid userId, valid friendUserId
###
POST http://localhost:8081/friend/addByUserId
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be37",
    "friendUserId" : "65deb6a2c488f1a40b1b85cd"
}

# Should Fail: valid userId, invalid friendUserId
###
POST http://localhost:8081/friend/addByUserId
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "friendUserId" : "hdfhfgh43534"
}

# Should Pass: Valid userId, valid friendUserId
###
DELETE http://localhost:8081/friend/deleteByUserId
Content-Type: application/json 

{
    "userId": "65deb3d6336c535c1f70be27",
    "friendUserId": "65deb6a2c488f1a40b1b85cd"
}

# Should Fail: invalid userId, Valid friendUserId
###
DELETE http://localhost:8081/friend/deleteByUserId
Content-Type: application/json 

{
    "userId": "65deb3d6336c535c1f70be24",
    "friendUserId": "65deb6a2c488f1a40b1b85cd"
}

# Should Fail: Valid userId, invalid friendUserId
###
DELETE http://localhost:8081/friend/deleteByUserId
Content-Type: application/json 

{
    "userId": "65deb3d6336c535c1f70be27",
    "friendUserId": "65deb6a2c488f1a40b1b85ce"
}

# Should Pass: Valid userId
###
GET http://localhost:8081/friend/getByUserid/65deb3d6336c535c1f70be27
Content-Type: application/json 

# Should Fail: invalid userId
###
GET http://localhost:8081/friend/getByUserid/65deb3d6336c535c1f70be23
Content-Type: application/json 

# Should Pass: Should Return all Friends
###
GET http://localhost:8081/friend/
Content-Type: application/json
