POST http://localhost:8081/friend/addByUsername
Content-Type: application/json 

{
    "username" : "testtest",
    "friendUsername" : "huthifa"
}

###
GET http://localhost:8081/friend/
Content-Type: application/json
