POST {{$processEnv REACT_APP_API_URL}}/user/signup
Content-Type: application/json 

{
    "username" : "huthifaTest",
    "email" : "huthifaTest@gmail.com",
    "password" : "huthifa222"
}

###
POST {{$processEnv REACT_APP_API_URL}}/user/login
Content-Type: application/json 

{
    "username" : "huthifaTest",
    "password" : "huthifa222"
}


###
GET {{$processEnv REACT_APP_API_URL}}/user/
Content-Type: application/json

###
POST {{$processEnv REACT_APP_API_URL}}/user/editUser
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "username" : "TochiEdit",
    "email" : "test@gmail.com",
    "password" : "dwwrwrabc"
}

###
GET  {{$processEnv REACT_APP_API_URL}}/user/getUserById
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27"
}

# DO NOT RUN THIS TEST (It will delete all the users
###
# POST  {{$processEnv REACT_APP_API_URL}}/user/deleteAll