POST http://localhost:8081/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###
POST http://localhost:8081/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}


###
GET http://localhost:8081/user/
Content-Type: application/json

###
POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27",
    "username" : "TochiEdit",
    "email" : "test@gmail.com",
    "password" : "dwwrwrabc"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "65deb3d6336c535c1f70be27"
}

# DO NOT RUN THIS TEST (It will delete all the users
###
# POST  http://localhost:8081/user/deleteAll